export const CONFIG_VERSION = 1;
export const DEFAULT_COMMAND_NAME = "pi";
export const DEFAULT_GLOBAL_CONCURRENCY = 2;
export const DEFAULT_PRIMARY_FLUSH_MS = 1200;
export const DEFAULT_QUEUE_LEASE_MS = 90_000;
export const MAX_CONTEXT_LINES = 100; // Upper limit guardian
export const MAX_CONTEXT_CHARS = 32_000; // Upper limit guardian
export const DEFAULT_CONTEXT_LINES = 50; // Default, overrideable per-route
export const DEFAULT_CONTEXT_CHARS = 16_000; // Default, overrideable per-route
export const DISCORD_MESSAGE_LIMIT = 1900;
